### PR TITLE
Added Python 3 compatibility

### PR DESCRIPTION
**Pull request by BZhong7**
Hey this is Brandon Zhong, the intern on Nougit.
I added Python 3 compatibility to pdfmerge and will be testing code submission on NouGit.

### CODE REVIEW

**Review by StewartNoyce — COMMENTED** [review]
Brandon, I have an odd problem on the machine that is running python 2.7 and python 3.2.  The python 3 version says it can't find PyPDF2, but the pip install PyPDF2 says that it is already available.  The issue seems to be that the library is here - /Library/Frameworks/Python.Framework/Versions/2.7/site-packages.  I had upgraded the pip version to the latest (20.1.1) with sudo pip install --upgrade pip.  That version started the 'pip install PyPDF2' with a DEPRECATION statement, saying Python 2.7 was no longer supported as of January 2020.  Yet, it somehow still believes that the old site packages folder was going to work.  Any thoughts?

**Comment by BZhong7** [comment]
Did you try pip3 install PyPDF2? When installing with pip, it defaults to the Python 2 directories for installation. You need to use pip3 to install modules for Python 3 or else it won't be found.

I also updated pip to version 20.1.1 and looked at the DEPRECATION message. It looks like Python 2.7 is no longer being maintained and pip will drop support for it next year. For now, you can still use it to install modules for Python 2.7 and should work as intended.

**Comment by StewartNoyce** [comment]
Thanks for the suggestion.  I will try pip3 next.  There is also an option to use "python3 -m pip install PyPDF2".

**Comment by StewartNoyce** [comment]
Ok, I got it to work only after loading the most recent version of Python (3.8).  pip3 wasn't in the previous install, and this was the only way to get it.  The pull request looks good to go.

**Pull request merged**
